_target_: concept_graphs.perception.segmentation.AutomaticMobileSAM.AutomaticMobileSAM
mask_generator:
  _partial_: true
  _target_: mobile_sam.SamAutomaticMaskGenerator
  box_nms_thresh: .5
  pred_iou_thresh: .94
model_type: "vit_t"
checkpoint_path: ${checkpoint_path}/mobile_sam.pt
device: cuda