_target_: concept_graphs.perception.segmentation.AutomaticMobileSAM.AutomaticMobileSAM
mask_generator:
  _partial_: true
  _target_: mobile_sam.SamAutomaticMaskGenerator
  box_nms_thresh: 0.5
  pred_iou_thresh: 0.88
#  box_nms_thresh: .5
#  points_per_side: 12
#  points_per_batch: 144
#  pred_iou_thresh: 0.88
#  stability_score_thresh: 0.95
#  crop_n_layers: 0
#  min_mask_region_area: 100

model_type: "vit_t"
checkpoint_path: ${cache_dir}/mobile_sam.pt
device: ${device}