_target_: concept_graphs.perception.segmentation.GridMobileSAM.GridMobileSAM
grid_width: 5
grid_height: 5
grid_jitter: true
model_type: "vit_t"
checkpoint_path: ${cache_dir}/mobile_sam.pt
device: cuda
nms_iou_threshold: 0.5
min_mask_area_px: 49