_target_: concept_graphs.perception.segmentation.GridMobileSAM.GridMobileSAM
grid_width: 8
grid_height: 8
model_type: "vit_t"
checkpoint_path: ${checkpoint_path}/mobile_sam.pt
device: cuda
nms_iou_threshold: 0.5