_target_: concept_graphs.perception.segmentation.SAM3.SAM3
model_type: sam3
bpe_path: ${cache_dir}/bpe_simple_vocab_16e6.txt.gz
queries_path: ${cache_dir}/procthor_classes.txt
threshold: 0.5
sam_batch_size: 30 # Adjust based on your GPU memory
device: ${device}
