_target_: rgbd_dataset.rgbd_dataset.datasets.Scannetpp.ScannetppCOLMAP
dataset_name: "scannetpp"
base_path: ???
scene: 4318f8bb3c
width: 1920
height: 1440
fx: 1437.56
fy: 1437.54
cx: 956.874
cy: 723.627
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 50
relative_pose: False
depth_scale: 1000.0
point_cloud: False
depth_trunc: 8.0
