_target_: rgbd_dataset.datasets.Unreal.Unreal
dataset_name: "unreal"
base_path: ???
scene: bistro_scene
width: 1920
height: 1080
fx: 2828.2831640142235
fy: 2828.2831640142235
cx: 960
cy: 540
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 50
relative_pose: False
depth_scale: .01
point_cloud: true
depth_trunc: 8.0
