defaults:
  - algo: CGDetector
  - dataset: SemiStaticSim
  - paths: paths
  - _self_

name: cg-detector
sim_thresh: 0.90
overlap_eps: 0.025
voxel_size: 0.025
denoising_eps: 0.1
max_points_pcd: 8000
final_min_segments: 2

device: cuda
debug: true
caption: false
tag: false
save_map: true
seed: 123

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 1
  shuffle: false
  num_workers: 2
  pin_memory: false
  collate_fn:
    _target_: rgbd_dataset.rgbd_dataset.dataloader.collate_fn_np_single_cb
