# @package _global_
defaults:
  - base
  - /ft_extraction: CLIP
  - override /segmentation: YoloMobileSAM
  - _self_

final_min_segments: 5

name: cg-detector

perception:
  segment_scoring_method: area
  bg_sim_thresh: 0.615
  crop_bg_color: null # Keep bg

mapping:
  similarity:
    _target_: concept_graphs.mapping.similarity.Similarity.CombinedSimilarity
    geometric_similarity:
      _target_: concept_graphs.mapping.similarity.geometric.RadiusOverlap
      agg: max
      eps: 0.1
    semantic_similarity:
      _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01
    geometric_sim_thresh: 0.2
    semantic_sim_thresh: 0.2
    sim_thresh: 0.79
  object_factory:
    _target_: concept_graphs.mapping.Object.RunningAverageObjectFactory
    semantic_mode: mean
    geometry_mode: pcd
    n_sample_pcd: 200
  n_min_segments: 3
  grace_min_segments: 30
  filter_min_every: 10
  collate_objects_every: 1
  self_merge_every: 5
  downsample_every: 5
  denoise_every: -1
  device: cpu