# @package _global_
defaults:
  - /ft_extraction: CLIP_H14
  - /vlm@vlm_verifier: OpenAIVerifier
  - /inference: QueryReceptacles
  - _self_

name: "map_receptacles"

semantic_similarity:
  _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01

vlm_verifier:
  max_images: 5
  retry_attempts: 3
  verify_mode: majority_vote   # Options: majority_vote, unanimous, single