defaults:
  - pcd_callbacks@object_factory.denoising_callback: DBSCAN
  - pcd_callbacks@object_factory.downsampling_callback: VoxelDownSampling
  - similarity: Similarity

_target_: concept_graphs.mapping.ObjectMap.ObjectMap
object_factory:
  _target_: concept_graphs.mapping.Object.ObjectFactory
  segment_heap_size: 12
  geometry_mode: "pcd"

min_segments: 4
self_merge_every: 10
filter_min_every: -1
collate_objects_every: 5

device: cuda