defaults:
  - pcd_callbacks@denoising_callback: DBSCAN
  - pcd_callbacks@downsampling_callback: VoxelDownSampling
  - similarity: Similarity

_target_: concept_graphs.mapping.ObjectMap.ObjectMap
object_factory:
  _target_: concept_graphs.mapping.Object.ObjectFactory
  segment_heap_size: 12
  geometry_mode: "centroid"

min_segments: 4
self_merge_every: 10
filter_min_every: -1
denoise_pcd_every: 10
downsample_pcd_every: 10

device: cuda