defaults:
  - pcd_callbacks@denoising_callback: DBSCAN
  - pcd_callbacks@downsampling_callback: VoxelDownSampling

_target_: concept_graphs.mapping.ObjectMap.ObjectMap
max_centroid_dist: .3
semantic_sim_thresh: .7
min_segments: 4

self_merge_every: 10
filter_min_every: -1
denoise_pcd_every: 10
downsample_pcd_every: 10

device: cuda