defaults:
  - pcd_callbacks@denoising_callback: RemoveStatOutlier
  - pcd_callbacks@downsampling_callback: VoxelDownSampling

_target_: concept_graphs.mapping.ObjectMap.ObjectMap
max_centroid_dist: .3
semantic_sim_thresh: .7
min_segments: 4
device: cuda