_target_: concept_graphs.mapping.similarity.Similarity.CombinedSimilarity
geometric_similarity:
    _target_: concept_graphs.mapping.similarity.geometric.PointCloudOverlapClosestK
    agg: max
    eps: 0.1
    k: 4
semantic_similarity:
  _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01
geometric_sim_thresh: 0.2
semantic_sim_thresh: 0.2
sim_thresh: 0.6