_target_: concept_graphs.mapping.similarity.Similarity.Similarity
geometric_similarity:
    _target_: concept_graphs.mapping.similarity.geometric.RadiusOverlap
    agg: max
    eps: 0.1
semantic_similarity:
  _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01
geometric_sim_thresh: 0.6
semantic_sim_thresh: 0.85