_target_: concept_graphs.mapping.similarity.Similarity.Similarity
geometric_similarity:
    _target_: concept_graphs.mapping.similarity.geometric.PointCloudOverlapClosestK
    agg: max
    eps: ${overlap_eps}
    k: 10
semantic_similarity:
  _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01
geometric_sim_thresh: 0.5
semantic_sim_thresh: 0.5