_target_: concept_graphs.perception.PerceptionPipeline.PerceptionPipeline
segmentation_model: ???
ft_extractor: ???
depth_trunc: 8.0
inflate_bbox_px: 10
bg_color: 0  # null: keep bg, 0: black, 255: white