_target_: concept_graphs.perception.PerceptionPipeline.PerceptionPipeline
segmentation_model: ???
ft_extractor: ???
depth_trunc: 8.0
inflate_bbox_px: 10
mask_subtract_contained: true
bg_classes:
  - wall
  - floor
  - ceiling
  - wall with holes
  - floor with holes
bg_sim_thresh: 0.605
crop_bg_color: null  # null: keep bg, 0: black, 255: white
semantic_similarity:
  _target_: concept_graphs.mapping.similarity.semantic.CosineSimilarity01
